import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

// styles.css is generated: every styles/*.css concatenated in name order (00-base, 20-render, …).
function buildStyles() {
  const dir = 'styles';
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.css')).sort();
  const out = files.map((f) => `/* ==== ${f} ==== */\n` + fs.readFileSync(path.join(dir, f), 'utf8')).join('\n\n');
  fs.writeFileSync('styles.css', out);
}
buildStyles();


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, see the src/ directory of vaire-obsidian
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: false,
});

if (prod) {
  await context.rebuild();
  buildStyles();
  process.exit(0);
} else {
  await context.watch();
}
