// Type badge colouring (feat/type-colors). Computes one `<style id="vaire-type-colors">`
// in `document.head` mapping every type slug seen across the vault's packages to a
// `--vaire-type-color` CSS custom property, light and dark variants, so
// `.vaire-type-<t>` elements (id refs, the node header badge, the node panel badge — see
// styles/00-base.css and styles/20-render.css) pick up a colour without any of them
// having to know where it came from. See BRANCHES.md `feat/type-colors` and
// `src/theme/families.ts` for the two colouring strategies this switches between.
//
// Recomputed:
//  - once the workspace layout is ready (packages have had a chance to scan);
//  - on `'settings-changed'` (the source, or a package's `vaire-renderer.toml`-derived
//    colours, may have changed);
//  - on `'renderer-config-changed'` (src/packages.ts — a package's `vaire-renderer.toml`
//    was created or modified);
//  - on `'local-index-rebuilt'` (src/packages.ts — fired once after Obsidian's metadata
//    cache reports `'resolved'` on a cold start; closes the gap where `onLayoutReady` runs
//    before `PackageRegistry.init()`'s async manifest reads have actually populated
//    `plugin.packages`, which would otherwise leave the very first paint uncoloured).
//
// `source: 'off'` removes the stylesheet entirely rather than injecting an empty one —
// `.vaire-type-<t>` elements then fall back to plain CSS (`var(--vaire-type-color,
// inherit)`), i.e. today's neutral badge.

import type { PackageInfo } from '../packages';
import type VairePlugin from '../main';
import { colorFor, type TypeColorConfig, type TypeColorSource } from './families';

const STYLE_EL_ID = 'vaire-type-colors';

export function registerTypeColors(plugin: VairePlugin): void {
  const recompute = (): void => updateStyle(plugin);

  plugin.app.workspace.onLayoutReady(recompute);
  plugin.registerEvent(plugin.events.on('settings-changed', recompute));
  plugin.registerEvent(plugin.events.on('renderer-config-changed', recompute));
  plugin.registerEvent(plugin.events.on('local-index-rebuilt', recompute));

  plugin.register(() => {
    document.getElementById(STYLE_EL_ID)?.remove();
  });
}

function updateStyle(plugin: VairePlugin): void {
  const existing = document.getElementById(STYLE_EL_ID) as HTMLStyleElement | null;
  const source = plugin.settings.typeColorSource;

  if (source === 'off') {
    existing?.remove();
    return;
  }

  const css = buildCss(plugin.packages.all(), source);
  if (!css) {
    existing?.remove();
    return;
  }

  const styleEl = existing ?? document.head.appendChild(document.createElement('style'));
  styleEl.id = STYLE_EL_ID;
  styleEl.textContent = css; // replaced wholesale on every recompute, never appended to
}

/** Every type slug actually seen in `pkg`: declared in `knowledge.toml`'s `types` and/or
 *  actually carried by an indexed node — the union, since either source alone can be
 *  incomplete (a stale/hand-written manifest; a type nobody has authored a node of yet). */
function typesOf(pkg: PackageInfo): string[] {
  const set = new Set<string>(pkg.types);
  for (const type of pkg.index.byType().keys()) set.add(type);
  return [...set];
}

/**
 * One `--vaire-type-color` rule per type per theme, under `body:not(.theme-dark)` /
 * `body.theme-dark` (Obsidian's own theme class — see `app.js`'s `setTheme`). A type seen
 * in more than one package keeps whichever package's colour it got first, per `packages`'
 * iteration order — "first package wins", as specified.
 */
function buildCss(packages: PackageInfo[], source: TypeColorSource): string {
  const seen = new Set<string>();
  const light: string[] = [];
  const dark: string[] = [];

  for (const pkg of packages) {
    for (const type of typesOf(pkg)) {
      if (seen.has(type)) continue;
      seen.add(type);
      const config: TypeColorConfig = { source, renderer: pkg.rendererConfig };
      const cls = `vaire-type-${type}`;
      light.push(`body:not(.theme-dark) .${cls} { --vaire-type-color: ${colorFor(type, config, 'light')}; }`);
      dark.push(`body.theme-dark .${cls} { --vaire-type-color: ${colorFor(type, config, 'dark')}; }`);
    }
  }

  if (!light.length) return '';
  return (
    '/* Generated by Vairë (registerTypeColors) — do not edit; replaced on every recompute. */\n' +
    [...light, ...dark].join('\n')
  );
}
